### ISSUE TITLE
Hello.Could you please send me the pre-trained model?

### ISSUE THREAD

**Issue by zoubaihan** [YangHan-Morningstar/garbage_classification_pro#2]
Hello.Could you please send me the pre-trained model?Espacially  the file "Bid_model.h5"?

**Comment by YangHan-Morningstar** [comment]
You can download it from the link below. If you like my project, please order a star to encourage me, thanks.
链接: https://pan.baidu.com/s/1bATRbqcnh8d6SWS9H0lzbA  密码: kbkn

**Comment by MX-netizen** [comment]
> Hello.Could you please send me the pre-trained model?Espacially the file "Bid_model.h5"?



> You can download it from the link below. If you like my project, please order a star to encourage me, thanks.
> 链接: https://pan.baidu.com/s/1bATRbqcnh8d6SWS9H0lzbA 密码: kbkn
Hello.Could you please send me the pre-trained model?Espacially the file "Bid_model.h5"?
