### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by MOYUHeiYiDiMo** [YangHan-Morningstar/garbage_classification_pro#3]
您好，我最近在做相关的算法，能否分享一下您的数据集，万分感谢

**Comment by YangHan-Morningstar** [comment]
华为云垃圾分类比赛数据集：https://modelarts-competitions.obs.cn-north-1.myhuaweicloud.com/garbage_classify/dataset/garbage_classify.zip
COCO数据集：https://cocodataset.org/#overview
