### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AdaBubble** [YangHan-Morningstar/garbage_classification_pro#4]
Hi,could you share me the pre-trained model?

**Comment by YangHan-Morningstar** [comment]
You can download the pre-trained model in this link: 
链接: https://pan.baidu.com/s/1Bsf9QXw_mM0Y9gOmVwKmrQ  密码: cejk

**Comment by AdaBubble** [comment]
I have received your pre_trained_model，thank you very much! ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;YangHan-Morningstar&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月22日(星期四) 晚上7:08
收件人:&nbsp;&quot;YangHan-Morningstar/garbage_classification_pro&quot;<garbage_classification_pro@noreply.github.com&gt;;
抄送:&nbsp;&quot;AdaBubble&quot;<2542517161@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YangHan-Morningstar/garbage_classification_pro] Help (#4)
